Homework 4 Done
4050/8ball-project pull request #6
Opened 2019-10-14 20:50 UTC by 4050

2019-10-15 13:39 UTC, yalantis-ios-school requested changes
не вижу второй части домашки, конкретно удаление

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject.xcodeproj/project.pbxproj
>  		851C543C2345DAFD00A99261 /* AnswerModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 851C543B2345DAFD00A99261 /* AnswerModel.swift */; };
не могу оставить комментарий на файл, потому оставлю тут. файл .DS_Store должен быть в гитигноре и не попадать в гит

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject.xcodeproj/project.pbxproj
> +		8581676D2352589500042718 /* Answers+CoreDataClass.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8581676B2352589500042718 /* Answers+CoreDataClass.swift */; };
вот эти два класса лежать на уровне проекта. такого быть не должно, перемести в соответствующуюю папку

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject.xcodeproj/project.pbxproj
>  		851C543C2345DAFD00A99261 /* AnswerModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 851C543B2345DAFD00A99261 /* AnswerModel.swift */; };
также, в проекте сейчас 5 варнингов, которые нужно фиксить

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject.xcodeproj/project.pbxproj
>  		851C543C2345DAFD00A99261 /* AnswerModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 851C543B2345DAFD00A99261 /* AnswerModel.swift */; };
в прошлом ревью писал, что нужно удалить Main.storyboard

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/AppDelegate.swift
> +            window?.rootViewController = UINavigationController(rootViewController: TabViewController())
нет необходимости в UINavigationController'е, не говоря уже о том, что он создаёт артефакт на представлении

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/AppDelegate.swift
> +    private let storageService = StorageAnswerService()
не понятно зачем это здесь. во-первых, ты создаешь эту зависимость и никуда не прокидываешь. в двух других местах ты так же создаешь их, и уже ними пользуешься, при этом у тебя нет никаких shared state

т.е. твои контейнеры, контексты и вот это вот всё внутри StorageAnswerService создаются каждый раз новые, и твой save в методе applicationWillTerminate вообще ничего не сохраняет

\+ сохраняешь данные ты сразу же при их создании, по месту

это похоже на какаую-то необдуманную копипасту. нужно убрать

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +        defaultAnswers = hardCodedAnswerViewModel.getMotivationAnswers()
во всех метода жизненного цикла контроллера обязательно нужно вызвать метод суперкласса

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +        super.loadView()
лучше для таких целей пользоватся методом `viewDidLoad`

метод `loadView` предназначен для переопределения рутовой вьюхи

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
старайся не пользоваться голыми строками в коде. в данном случае можно воспользоваться `String(describing: UITableViewCell.self)`

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +        tableView.reloadData()
этот вызов делает ровным счетом ничего. во-первых, при установке дата сорса таблице она сама это делает. во-вторых, во viewWillAppear ты дублируешь этот метод

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +
непонятная пустая строка

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject.xcodeproj/project.pbxproj
>  		851C543C2345DAFD00A99261 /* AnswerModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 851C543B2345DAFD00A99261 /* AnswerModel.swift */; };
все изменения у тебя слиты одним коммитом. такой объем работы нужно разбивать на куски. например, написал новый сервис (старый не удалил) - закоммитил. удалил старый сервис, сделай чтение с нового - закоммитил. сделай обновление данных - закоммитил. и тд

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/ResponseViewController.swift
> -        let hardCodedAnswerViewModel =
в предыдущей версии проекта у тебя было сохранение кастомных вариантов. сейчас этого не вижу, надо добавить

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/TabViewController.swift
> +            secondVC.viewWillAppear(true)
этот метод срабатывает автоматически (сдк ссама всё делает), не нужно его руками вызывать

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Model/HardCodedAnswersModel.swift
>      func getSaveAnswer() -> Answer {
именование хромает. два глагола подряд

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Model/ResponseModel.swift
> +                self.storageAnswer.saveAnswer(answer: response!)
избавься от форс анврапа (`!`)

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +    lazy var  backgroundMOC = persistentContainer.newBackgroundContext()
затесался пробел

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +                print("Saved")
принт нужно убрать

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +    func saveContex() {
метод используется только с делегата, так что можно будет убрать вообще

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +            return (fetchedObjects?.map {$0.toAnswer()})!
это нечитаемо, в добавок еще и содержит force unwrap

нужно переписать

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +        let taskObject = NSManagedObject(entity: entity!, insertInto: backgroundMOC) as! Answers
тут тоже нужно убрать два force unwrap

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/ViewModel/HardCodedAnswersViewModel.swift
> +        print("viewModel\(answers)")
принт подчистить нужно

2019-10-15 13:39 UTC, yalantis-ios-school commented on 8ball_testproject/CoreData/Answers+CoreDataClass.swift
> +public class Answers: NSManagedObject {
именование вводит в ступор)

у тебя как минимум должно быть единственно число. что-то вроде ManagedAnswer больше подойдет

2019-10-16 20:19 UTC, 4050 commented on 8ball_testproject.xcodeproj/project.pbxproj
>  		851C543C2345DAFD00A99261 /* AnswerModel.swift in Sources */ = {isa = PBXBuildFile; fileRef = 851C543B2345DAFD00A99261 /* AnswerModel.swift */; };
Удаление не реализовал, так как его не было изначально в ТЗ

2019-10-17 10:30 UTC, yalantis-ios-school approved these changes
оставшиеся комментарии нужно пофиксить перед следующей домашкой. как пофиксишь сам закрывай PR

2019-10-17 10:30 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +                // Очень надеюсь, что так делать не запрещено
ну поскольку в дз прямого такого условия небыло, то не запрещено, если у тебя всё работает

а у тебя всё работает

но в будущем стоит переделать под FRC, т.к. сейчас это костыль и оно а) выглядит топорно б) требует постоянных изменений при добавлении новых фичей

2019-10-17 10:30 UTC, yalantis-ios-school commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +                self.defaultAnswers = self.hardCodedAnswerViewModel.getMotivationAnswers()
массив с ответами должен жить в модели, или максимум в VM, но никак не в контроллере

2019-10-17 10:30 UTC, yalantis-ios-school commented on 8ball_testproject/Resources/AnswerWarehouse.xcdatamodeld/AnswerWarehouse.xcdatamodel/contents
> +    <entity name="ManageAnswer" representedClassName="ManageAnswer" syncable="YES">
`Managed`, не `Manage`. второе это глагол, а первое имя существительное

2019-10-17 10:30 UTC, yalantis-ios-school commented on 8ball_testproject/Services/StorageAnswerService.swift
> +    func saveContex() {
неиспользуемый метод

2019-10-17 21:35 UTC, 4050 commented on 8ball_testproject/Controller/HardCodedAnswersTableViewController.swift
> +                // Очень надеюсь, что так делать не запрещено
Тогда получается мне к следующей сдачи ДЗ надо его переделать ? Или оставить так ?

2019-10-19 18:10 UTC, merged